[package]
name = "wasm-tiny-png"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tiny-png = { path = "../..", default-features = false }

[profile.release]
opt-level = "z"
lto = true
